### PR TITLE
Setup

### PR DESCRIPTION
**Pull request by astroboyReloaded**
## For this exercise, I did the following: 📑 
- Run `npx create-react-app math-magicians`. 🛠️ 
- Create [this]([linters-config](https://github.com/microverseinc/linters-config)/react-redux/) repo. ✨ 
- Add  and make **Development** branch de default branch. 🌿
- Insatll **linters** and add files based on [linters-config](https://github.com/microverseinc/linters-config)/react-redux/. 👮 

😎

### CODE REVIEW

**Review by levy002 — COMMENTED** [review]
## Hello @astroboyReloaded 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :red_circle: :red_circle: 

You have submitted a project, that doesn't have a professional README file. 

  - [ ] Kindly make sure to use the [Microverse Readme template](https://github.com/microverseinc/readme-template) and make sure to remove all comments and instructions on how it must be filled and make sure to customize it according to your project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Tufahel — APPROVED** [review]
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

Hi @astroboyReloaded :wave: 
 
Your project is complete now!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 👏🏻



:heavy_check_mark: Linter checks are passing.
:heavy_check_mark: Readme is professional.
:heavy_check_mark: React app is working fine.


## Optional suggestions 🤷‍♂️

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.
- You can mail me at [Mail](mailto:tufahel96@gmail.com) or ask any question at Slack, `Name: Tufahel`

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by astroboyReloaded** [comment]
Thank you!

**Comment by astroboyReloaded** [comment]
Thank you!

**Comment by Tufahel** [comment]
> Thank you!

@astroboyReloaded, Hello, can you please confirm for me that in your dashboard, this project is approved? While I was submitting my review I saw an error on my end. That's why I am asking this question. Thanks.

**Pull request merged**
